### PR TITLE
Upgrade `Icon` docspage and storybook stories

### PR DESCRIPTION
**Pull request by justinanastos**
My goal here was to make the chromatic diffs more useful because whenever we change _anything_, it's incredibly hard to see what actually changed. This will give us individual stories for each icon and will show them nicely in a docs page.

<details>
  <summary>📦 Published PR as canary version: <code>7.14.2-canary.235.5208.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @apollo/space-kit@7.14.2-canary.235.5208.0
  # or 
  yarn add @apollo/space-kit@7.14.2-canary.235.5208.0
  ```
</details>

### CODE REVIEW

**Comment by jglovier** [comment]
I'm a huge fan of this. It's going to make Chromatic reviews much more friendly. Thanks for implementing this one!! 
giggle

**Review by jglovier — APPROVED** [review]
🚢

**Review by jgzuke — COMMENTED** [review]
Iirc we pay chromatic per story? I dont remember how much though (or even if it was enough to be worth considering in this case), might be worth adding here for context?

**Comment by justinanastos** [comment]
> Iirc we pay chromatic per story? I dont remember how much though (or even if it was enough to be worth considering in this case), might be worth adding here for context?

@jgzuke We do pay by the snapshot. We get 35k included in our current plan and we used 11.3k last month. When we go over it'll cost $0.005/snapshot, costing $0.75 per CI build for the icons. I think that's worth the easier reviews and better format here.

**Comment by apollo-bot2** [comment]
:rocket: PR was released in [`v7.15.0`](https://github.com/apollographql/space-kit/releases/tag/v7.15.0) :rocket:

**Pull request merged**
