### PR TITLE
Add solid time icon

### PR DESCRIPTION
**Pull request by esilverm**
This PR adds a new version of the time icon to indicate initiated launches

It also fixes a minor spelling error in the icon guide

### CODE REVIEW

**Review by cheapsteak — APPROVED** [review]
⌛

**Comment by apollo-bot2** [comment]
:rocket: PR was released in [`v8.22.0`](https://github.com/apollographql/space-kit/releases/tag/v8.22.0) :rocket:

**Comment by jgzuke** [comment]
@esilverm random Q. Did this come from streamline (our icon library)? If so we should probably mark it as `-sl` so we can track our usage limit

**Comment by jglovier** [comment]
@esilverm for historical reference, could you please include a screenshot for any PR that adds an icon (similar to #294 and #286)? I realize you can see it in Chromatic while the PR is open, but after it's been closed you can no longer see the change so it's a helpful signal for folks that come along after merging. Thanks!

**Comment by esilverm** [comment]
> @esilverm for historical reference, could you please include a screenshot for any PR that adds an icon (similar to #294 and #286)? I realize you can see it in Chromatic while the PR is open, but after it's been closed you can no longer see the change so it's a helpful signal for folks that come along after merging. Thanks!

Thanks for giving me a heads up. I checked prior PRs that added icons to see if they did this, but didn't see anything so I assumed it didn't matter. I guess I didn't see those two. I'll be sure to remember to do this for next time!

**Comment by jglovier** [comment]
@esilverm yeah, I admit we have been kind of inconsistent with that. 🙈 😊

**Pull request merged**
