### PR TITLE
Fix Popover component not being able to render >800 times without taking a dump on the main thread

### PR DESCRIPTION
**Pull request by brainkim**
<details>
  <summary>📦 Published PR as canary version: <code>9.1.1-canary.357.9555.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @apollo/space-kit@9.1.1-canary.357.9555.0
  # or 
  yarn add @apollo/space-kit@9.1.1-canary.357.9555.0
  ```
</details>

### CODE REVIEW

**Review by cheapsteak — APPROVED** [review]
Sweet, and thank you!
I'm surprised that just memoizing modifiers is enough, were the props like content and children red herring?

**Comment by cheapsteak** [comment]
Should we do similarly for AbstractTooltip etc?

**Comment by brainkim** [comment]
@cheapsteak I was thinking about this in the shower. Before we merge, one alternative is to define the callbacks at the module scope, so we don’t have to use `useMemo()`. The thing is, the problem would still exist if the `fallbackPlacements` variable changed, albeit at a much slower pace.

**Comment by apollo-bot2** [comment]
:rocket: PR was released in [`v9.2.0`](https://github.com/apollographql/space-kit/releases/tag/v9.2.0) :rocket:

**Pull request merged**
