### PR TITLE
Update overflow icon

### PR DESCRIPTION
**Pull request by jglovier**
Tweaks styles for the overflow icon to be a little less big and puffy and a little more spacious (i.e. more standardized).

| Before | After |
|---|---|
| image |image|

### CODE REVIEW

**Comment by jglovier** [comment]
Oddly enough, the Chromatic changes for this branch seem to be broken or not working correctly. The only diff that came up for this change was for the tooltip with normal padding (which I didn't change), and the icon view didn't actually show the diff.

Also, I'm noticing that the teal version doesn't change color, even though the fill on the path is set to `#000`. 🤔 

image

**Comment by jglovier** [comment]
Nevermind, switching the fill value from `#000` to `#000000` seems to have fixed it. I thought `#000` worked too.

**Comment by Jephuff** [comment]
> Nevermind, switching the fill value from `#000` to `#000000` seems to have fixed it. I thought `#000` worked too.

huh, I thought #000 would work as well, it's in the list of things to replace 🤔

**Comment by jglovier** [comment]
Weird that the Chromatic tests still aren't picking up a change for the icon though. Perhaps another argument for separating icon tests out into their own stories as @justinanastos was saying.

**Comment by apollo-bot2** [comment]
:rocket: PR was released in [`v7.3.0`](https://github.com/apollographql/space-kit/releases/tag/v7.3.0) :rocket:

**Pull request merged**
