### PR TITLE
Add guide for icon development

### PR DESCRIPTION
**Pull request by jglovier**
This PR adds a guide to Storybook for icon development for handy reference.

image

<details>
  <summary>📦 Published PR as canary version: <code>8.17.4-canary.328.8747.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @apollo/space-kit@8.17.4-canary.328.8747.0
  # or 
  yarn add @apollo/space-kit@8.17.4-canary.328.8747.0
  ```
</details>

### CODE REVIEW

**Comment by jglovier** [comment]
Hmm, it's not clear to me why this eslint test is failing. 🤔 I don't see the html entity on that line that matches what it's talking about...

image

**Comment by justinanastos** [comment]
> Hmm, it's not clear to me why this eslint test is failing. 🤔 I don't see the html entity on that line that matches what it's talking about...
> 
> image

@jglovier 

The error message is not clear. Prettier is complaining about a trailing space on line 34.
image

You can have eslint automatically fix this at development-time by setting up eslint in VS Code. Or you can run the linter in autofix mode from the command line with this command and the eslint error will fix itself.

```
npm run lint -- --fix
```

**Review by justinanastos — APPROVED** [review]

**Comment by jglovier** [comment]
@justinanastos gah - I didn't realize I had never setup eslint for this repo. Thank you!!

**Comment by jglovier** [comment]
Hmm, it looks like I did have eslint configured on this project, but wondering if it just didn't run on save because this particular file is a `.mdx` file? Would that matter?

**Comment by justinanastos** [comment]
> So I did have eslint configured for this repo, but looks like `editor.codeActionsOnSave` was set to `null`. However, even after updating it to:
> 
> ```
> "editor.codeActionsOnSave": {
>         "source.fixAll.eslint": true
>       },
>     "eslint.validate": ["javascript"],
> ```
> 
> ...it's still not fixing the trailing space after I added it back in to test and saved the file.
> 
> Is that maybe because this particular file is a `.mdx` file? Would that matter? Do I need to add that file type to the `eslint.validate` value?

That's puzzling. We have a vs code config in source control that indicates that we should lint `.mdx` files:

https://github.com/apollographql/space-kit/blob/7b6e54879af4e95f8bdef0b627613d5dce4904e2/.vscode/settings.json#L9

I don't know why it didn't work :(

**Comment by justinanastos** [comment]
@jglovier 

> So I did have eslint configured for this repo, but looks like `editor.codeActionsOnSave` was set to `null`. However, even after updating it to:
> 
> ```
> "editor.codeActionsOnSave": {
>         "source.fixAll.eslint": true
>       },
>     "eslint.validate": ["javascript"],
> ```
> 
> ...it's still not fixing the trailing space after I added it back in to test and saved the file.
> 
> Is that maybe because this particular file is a `.mdx` file? Would that matter? Do I need to add that file type to the `eslint.validate` value?

That's puzzling. We have a vs code config in source control that indicates that we should lint `.mdx` files:

https://github.com/apollographql/space-kit/blob/7b6e54879af4e95f8bdef0b627613d5dce4904e2/.vscode/settings.json#L9

I don't know why it didn't work :(

**Comment by apollo-bot2** [comment]
:rocket: PR was released in [`v8.17.4`](https://github.com/apollographql/space-kit/releases/tag/v8.17.4) :rocket:

**Pull request merged**
